### ISSUE TITLE
session.py issue line 125

### ISSUE THREAD

**Issue by dfriestedt** [refindlyllc/rets#119]
I had to change line 125 from:

self._request(self.capabilities['Action'])
to 
self._request('Action')

The old line was passing in the entire URL.  I believe the function only needs the word 'Action'.  Am I thinking about this wrong?

**Comment by mcrowson** [comment]
Good catch!

**Comment by mcrowson** [comment]
I'm writing a test for it and don't currently have access to a board that has an Action requirement. Do you mind providing a sample response to the Action request?

**Comment by mcrowson** [comment]
I think this calls the Action endpoint correctly, but I don't have a feed to test against. So please reopen if it is not addressed. Here is what the RETS standard says about Action

> A URL on which the client MUST perform a GET
> immediately after login. This might include a bulletin or the
> notification of email. The client application SHOULD
> provide a means for the user to view the retrieved document.

Right now the library just makes a GET request to the action endpoint. Nothing is provided in terms of arguments like the email. Any other guidance or examples would be helpful. The current example in the test suite is a placeholder for now.
