### ISSUE TITLE
session.py issue line 118

### ISSUE THREAD

**Issue by dfriestedt** [refindlyllc/rets#120]
In Chicago, the MRED MLS needs the full 'RETS-Version' name. So stripping 'RETS/'  in line 118 of session.py throws a version error.  MRED needs 'RETS/1.7.2' or 'RETS/1.5'.  

self.version = str(parser.headers.get('RETS-Version')).strip('RETS/')

MRED requires the following:

self.version = str(parser.headers.get('RETS-Version'))

**Comment by mcrowson** [comment]
Fixed, thanks.
