### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by mmansour** [refindlyllc/rets#178]
Howdy. Thanks for building out this module and test suite. 

For some reason I can't login. 

My credentials are good when I test them on Rets MD:

https://retsmd.com/auth/

However, when I try to login using this module with my credentials I get the following error: 

"line 370, in _request
    raise NotLoggedIn(msg)
rets.exceptions.NotLoggedIn: GetMetadata tried but no valid endpoints was found. Did you forget to Login?"

login_url = '{http://myretsloginurl/login}'
username = '{my username}'
password = '{my password}'
rets_client = Session(login_url, username, password)
rets_client.login()
system_data = rets_client.get_system_metadata()
print system_data

I also tried passing in http_auth='basic' and a different rets version but no luck there. 

Any ideas on why my credentials do authenticate on https://retsmd.com/auth/ but not with this module? 

Best,
Matt

**Comment by mcrowson** [comment]
Mind sharing some details on the rets server and vendor? 

RETS Version Number:
Vendor Name:
Board Name:
Authentication method:


If you log into retsmd they have this metadata at the top normally.

**Comment by mcrowson** [comment]
My suspicion is this is due to the RETS version number in the headers. Can you download and test on that pull request?

**Comment by mmansour** [comment]
No luck on that change. I get the same error. 

I tried initiating the session with no version, and also with different versions:  '1.8', '1.7.2', '1.7' e.g. rets_client = Session(login_url, username, password, version='1.8')

Here is the server information I get when I log into retsmd. 


RETS Server: |  (this is blank)
-- | --
RETS System ID: |  (this is blank)
Login URL: | myretsloginurl
RETS Version: | 1.7.2
Server Software: | nginx
Authen. Supported: | Digest
Transactions Supported: | Login, Action, Search, GetMetadata, Logout, GetObject
Metadata Resources: | Agent, Office, Property, History, OpenHouse, Media, Deletions, ListingStatusHistory, City

I am in California/Los Angeles and going through CARETS

**Comment by mcrowson** [comment]
Looks like the server version is 1.7.2. Try no passing a version at all. If that still doesn’t work you can step through the login method and give the XML response that the server gives back when you try to login.

**Comment by mcrowson** [comment]
Also that PR has been updated to 0.4.2 if you just want to update your package.

**Comment by mmansour** [comment]
Interesting. When I step through the login method I get a 500 error on the response: 
"HTTP Status 500 - String index out of range: -13"

        line 114 response = self._request('Login')
        line 115 parser = OneXLogin()

**Comment by mcrowson** [comment]
Take a look at the payload and headers in the underlying _request() method. It just uses the requests library. Not sure what it being passed that it doesn't like.

**Comment by mmansour** [comment]
{'headers': {'Accept-Encoding': 'gzip', 'Accept': '*/*', 'User-Agent': 'Python RETS'}}

**Comment by mcrowson** [comment]
RETSmd sends a user agent as well. See if you can use the requests library to just hit the login with your credentials. 

If you want to email me the creds I can test too. We don’t have any clients in that market and don’t have access to the board. mattc@refindly.com.

**Comment by mmansour** [comment]
I got it working. I needed to pass in a board specific user_agent. Likewise, the RETS version my board is expecting looks like this "RETS/1.7" instead of just "1.7". 

Thanks for all the help and tips. 

And thanks again for open sourcing this library. Much appreciation.

**Comment by dariushazimi** [comment]
@mmansour how do you specify the user_agent and rest version.
Could you please provide a sample?

Thanks

**Comment by mmansour** [comment]
Hi @dariushazimi, I dug up the code of how I got it working in a Django 2017 app. 

That app is retired and it's been a long time. But this did work. Hope it still helps! 

Here's how I logged in

`rets_client = Session(settings.RETS_LOGIN_URL, settings.RETS_USER_NAME, settings.RETS_PASSWORD,
                                     user_agent=settings.RETS_USER_AGENT,
                                      version=settings.RETS_VERSION)
rets_client.login()`

Here's how I made a query for Residential Locations: Claw Residential Rentals > 10K per month

`search_results = rets_client.search(resource='Property',
                                                             resource_class='RNT', limit=5000,
                                                             dmql_query='(ListPrice=8000+),(ListingStatus=|ACTIVE)')`

Good luck!

**Comment by dariushazimi** [comment]
Thank you @mmansour for taking the time. Much appreciated.

**Comment by mybluedog24** [comment]
I just had exact the same issue, works in retsmd but not in this library. Found out the return error message is `"b'<RETS ReplyCode="20036" ReplyText="Missing or Invalid RETS Version" >\n</RETS>\r\n'"` and then found out retsmd code adds "RETS/" to the version in request, so yes add "RETS/1.7" instead of "1.7" as mmansour said. Wish it could show the actual error message for easier debug.
retsmd code:
`$rets->AddHeader("RETS-Version", "RETS/{$_SESSION['rets_version']}");`
