### ISSUE TITLE
session.login() returns True but subsequent calls fail if the server's session cookie name is not 'RETS-Session-ID'

### ISSUE THREAD

**Issue by drewgbarnes** [refindlyllc/rets#185]
It would be nice if login() threw an error in this case. 

I am working against a RETS server that does not use the standard session cookie name 'RETS-Session-ID', so while the login is "successful", the `session_id` is never set, so subsequent calls to other endpoints fail because the RETS-UA-Authorization header is incorrect due to the session_id not being included in the hash.

Following up with a PR to allow nonstandard cookie names, and punting on the error throwing from login().

**Comment by mcrowson** [comment]
Thanks for PR, address in release 0.4.4
