### ISSUE TITLE
Rapattoni Servers on non-standard ports 

### ISSUE THREAD

**Issue by bazeli** [refindlyllc/rets#190]
Hey there-

Much thanks for this helpful timesaver of a lib.   I ran into an issue with a Rapattoni RETS server running on a non-standard port (ie not 80 or 443).    After a bit of debugging, I made a small fix to support these cases.   Default behavior doesn't change for anyone - I decided to make it opt-in based on research done with other RETS servers.

Let me know if you would like me to create a PR.    Cheers!

[https://github.com/bazeli/rets/commit/3498de3e242b31faf39403061da1aea28b5b9a04](https://github.com/bazeli/rets/commit/3498de3e242b31faf39403061da1aea28b5b9a04)

**Comment by mcrowson** [comment]
Is there a reason why you wouldn't use the same port from the login url? I'm wondering if the copy_port parameter is necessary, or if one would always have the same port on the capabilities as the login url

**Comment by bazeli** [comment]
Agreed - that would be the more logical choice, but given the potential impact of the change I thought it best to make it optional.   Last thing anyone wants is broken code.   Up to you though.

**Comment by mcrowson** [comment]
You should see this in 0.4.5
