### ISSUE TITLE
Had to workaround bad characters in RETS open house response from Vancouver Island MLS feed

### ISSUE THREAD

**Issue by cynixinc** [refindlyllc/rets#192]
Got error "xml.etree.ElementTree.ParseError: reference to invalid character number: line 39, column 205" during RETS query - raised in rets/parsers/search.py

Cause was the following bad characters in the open house description not being parsable by ElementTree: `&#55357;&#56842;`

To quickly hack fix this I had to do this change...what's a robust way of handling this issue of characters in RETS responses that cannot be parsed by ElementTree?

`    def generator(self, response):
        """
        Takes a response socket connection and iteratively parses and yields the results as python dictionaries.
        :param response: a Requests response object with stream=True
        :return:
        """

        delim = '\t'  # Default to tab delimited
        columns = []
        response.raw.decode_content = True

        # Guy Neill workaround to bad chars in VIREB open house
        # events = ET.iterparse(BytesIO(response.content))
        **content_cleansed = response.content.replace('&#55357;&#56842;', '')
        events = ET.iterparse(BytesIO(content_cleansed))**`

**Comment by mcrowson** [comment]
interesting. Is this mostly to do with non-English characters? Worth making a PR?

**Comment by cynixinc** [comment]
This was an English language open house record in the RETS feed - probably invalid characters the MLS system allowed to be saved in the open house description.  Actual description text:

`<DATA>	27009	2018-04-21T05:18:48	2018-04-21T05:18:48	2018-04-21T22:00:00		81934	437388	2018-04-21 15:00:00	2018-04-21 13:00:00	Lakeview Home with bonus suite! Lots of parking at top of drive so come on up &#55357;&#56842;	2018-04-21T20:00:0</DATA>`

**Comment by cynixinc** [comment]
This issue has only occurred one time in the past year - may not be worth handling this since the characters are not supposed to be valid XML.

**Comment by mcrowson** [comment]
You're probably right. Closing this issue, but feel free to reopen if it turns out to be a recurring issue or one you feel that others might suffer from.
