### ISSUE TITLE
RETS client search returns empty results with City or L_City parameter

### ISSUE THREAD

**Issue by kevin-mccartney** [refindlyllc/rets#206]
With Python 3.7, and the current version of rets, I can successfully search on many different parameters e.g. State, ListPrice, L_ListingDate, etc. This works with either the dmql_query or search_filter parameters shown here:

` with Session(login_url, username, password) as rets_client: search_results = rets_client.search(resource='Property', resource_class='RE_1', limit=10, dmql_query=dmql_query_str)         #OR search_results = rets_client.search(resource='Property', resource_class='RE_1', limit=1, search_filter=sfilter)`

However, I get a search_results object with length zero back when I use either City or L_City as a parameter to dmql_query or search_filter, respectively:

`dmql_query_str = '(' + 'L_City=Casper' + ')'
#OR
    sfilter = { "L_City":"Casper" }
`
Searches performed with different parameters (i.e. State=WY, etc.) did find results with the L_City = Casper.

**Comment by mcrowson** [comment]
By previous you mean python versions <3.7? So the same request in 3.7 does not return results where the same request using 3.6 would?

**Comment by kevin-mccartney** [comment]
Clarification made. Not <3.7 versions of Python, rather previous searches that found the city "Casper" and make me expect I could search with that same string and get results.

**Comment by mcrowson** [comment]
Can you try and make the request to the RETS server in Postman or your browser and see what response it gives? Not sure if we're poorly formatting the request or the server just isn't giving the response it should.

**Comment by kevin-mccartney** [comment]
I can try a browser, though may I ask for a reference/an example of a URL that I can search with?

Here’s what I know

  1.  My credentials
  2.  Login page is
http://wyo-rets.paragonrels.com/rets/fnisrets.aspx/WYO/login?rets-version=rets/1.7.2

  1.  That page says

 Search=/rets/fnisrets.aspx/WYO/search

  1.  In Python, I’m basically using

[cid:image001.png@01D563C5.05F90290]

… so it’s not clear how to format the URL path with credentials and search parameters too.

Thanks,

Kevin

**Comment by kevin-mccartney** [comment]
Please let me know a reference or an example of said search with a URL path e.g. .../rets/fnisrets.aspx/... Thanks.

**Comment by kevin-mccartney** [comment]
Using Postman, I sent query:
`...search?SearchType=Property&Class=RE_1&Query=(L_State=WY)&Limit=1&rets-version=rets/1.7.2`
and got the results which includes <City>Casper</City>

However, with query just for that city:
`search?SearchType=Property&Class=RE_1&Query=(L_City=Casper)&Limit=1&rets-version=rets/1.7.2`
I get: <RETS-STATUS ReplyCode="20201" ReplyText="No Records Found." />

**Comment by mcrowson** [comment]
Yea, maybe reach out to the RETS vendor for the board and ask them just to see if we're missing something. Closing the issue as it seems to be a server-side issue, but if not feel free to reopen.
